<a href="https://colab.research.google.com/github/Baldorpau07/Ejercicios-PYTHON/blob/main/Matrices_clase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#siempre empezar con eso

In [ ]:
arr= np.array([1,2,3,4,5,6,7,8,9,10])
#da igual si pongo paréntesis o corchetes
print(arr)
print(type(arr))
arr1=np.array(42)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
42


In [ ]:
arr2=np.array((1,2,3,4,5))
print(arr2)

[1 2 3 4 5]


In [ ]:
arr3=np.array([[1,2,3],[1,2,3]])
print(arr3)

arr4=np.array([[[1,2,3],[4,5,6]],[[1,2,4],[4,5,6]]])
print(arr4)

[[1 2 3]
 [1 2 3]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 4]
  [4 5 6]]]


In [ ]:
arr1=np.array(42)
arr2=np.array((1,2,3,4,5))
arr3=np.array([[1,2,3],[4,5,6]])
arr4=np.array([[[1,2,3],[4,5,6]],[[1,2,4],[4,5,6]]])
print(arr1.ndim, arr1.shape)
print(arr2.ndim, arr2.shape)
print(arr3.ndim, arr3.shape)
print(arr4.ndim, arr4.shape)
#ndim es para ver qué dimensión tiene
#shape es para ver la forma de la matriz

0 ()
1 (5,)
2 (2, 3)
3 (2, 2, 3)


In [ ]:
arr5=np.array([1,2,3,4], ndmin=5)
print(arr5)
#ndmin forma que tu matriz tenga cierta dimensión
print(arr5.ndim, arr5.shape)


[[[[[1 2 3 4]]]]]
5 (1, 1, 1, 1, 4)


In [ ]:
arr2=np.array((1,2,3,4,5))
arr3=np.array([[1,2,3],[4,5,6]])
print(arr2[0])
#aquí accede al primer elemento de la matriz
print(arr3[0,1])
#aquí accede a la primera matriz y al segundo elemento
#en python las matrices empiezan a contar en 0 como en las listas

1
2


In [ ]:
#slicing
#se puede definir [inicio:fin]
#o se puede definir con el paso [inicio:fin:paso]

In [ ]:
arr2=np.array((1,2,3,4,5))
print(arr2[1:4])
#aquí se usa slicing en el qie imprime los que tú quieras poner [inicio:fin] pero curiosamente el fin es como una cota superior que no imprime, es el tope
print(arr2[1:4:2])
#este es el paso que sirve para saltarse alguna posición al imprimir
print(arr2[1:])
#este slicing es para que imprima desde la primera posición hasta el final (los sucesores que están en el arr2)
print(arr2[:4])
#imprime todos los antecesores hasta la posición 4


[2 3 4]
[2 4]
[2 3 4 5]
[1 2 3 4]


In [ ]:
arr3=np.array([[1,2,3],[4,5,6]])
print(arr3[0,:2])
#aquí le está diciendo a numpy, ve al primer vector e imprime todos sus elementos anteriores a la posición 2
arr4=np.array([[[1,2,3],[4,5,6]],[[1,2,4],[4,5,6]]])
print(arr4[0:2,0:2,0:2])
#ahí imprimió los primeros dos elementos de cada fila

[1 2]
[[[1 2]
  [4 5]]

 [[1 2]
  [4 5]]]


In [ ]:
arr8=np.array((1,2,3,4,5,6,7,8))
x=np.where(arr8==3)
#me da la el elemento en la posición 3 en el arr8
y=np.where(arr8%2==0)
#me da las posiciones de los números que son divisibles entre 2
print(x)
print(y)
z=np.searchsorted(arr8, 7)
print(z)
#searchsorted es más específico, en este caso busca la posiciíon del 7


(array([2]),)
(array([1, 3, 5, 7]),)
6


In [ ]:
#Filtrado
arr8=np.array((1,2,3,4,5,6,7,8))
filter_arr=arr8 >4
#aquellos que cumplen con la condición de ser mayores a 4
newarr=arr8[filter_arr]
print(filter_arr)
#imprime true quienes cumplen con la condición y false los que no (un buleano)
print(newarr)
#imprime los que cumplen con la condición


[False False False False  True  True  True  True]
[5 6 7 8]
